---
version: 1
formatters: 
  default: 
    format: '%(asctime)s | %(name)s - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  client:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: LOG.log
    when: W6
    backupCount: 3
    encoding: UTF-8
    level: DEBUG
  client_console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
loggers:
  PMACS:
    handlers: [client, client_console]
    level: DEBUG
    propogate: false